services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3.12.0
    restart: always
    ports:
      - "20034:8000"
    environment:
      WOODPECKER_OPEN: ${WOODPECKER_OPEN:-false}
      WOODPECKER_ADMIN: ${WOODPECKER_ADMIN}
      WOODPECKER_HOST: ${WOODPECKER_HOST}
      WOODPECKER_GITHUB: true
      WOODPECKER_GITHUB_CLIENT: ${GITHUB_CLIENT_ID}
      WOODPECKER_GITHUB_SECRET: ${GITHUB_CLIENT_SECRET}
      WOODPECKER_AGENT_SECRET: ${AGENT_SECRET}
      WOODPECKER_POLL_INTERVAL: ${WOODPECKER_POLL_INTERVAL:-5m}
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.12.0
    restart: always
    depends_on:
      - woodpecker-server
    environment:
      WOODPECKER_SERVER: woodpecker-server:9000
      WOODPECKER_AGENT_SECRET: ${AGENT_SECRET}
      WOODPECKER_BACKEND: docker
      WOODPECKER_BACKEND_DOCKER_VOLUMES: /etc/homelab/certs/ca/ca.crt:/etc/ssl/certs/homelab-ca.crt:ro
    volumes:
      - woodpecker-agent-config:/etc/woodpecker
      - /var/run/docker.sock:/var/run/docker.sock
      - nix-cache:/nix

volumes:
  woodpecker-server-data:
  woodpecker-agent-config:
  nix-cache:
